apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: c2E=                             # base64 encoded "sa"
  password: eW91clN0cm9uZyghKVBhc3N3b3Jk     # base64 encoded "yourStrong(!)Password"
