
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1533:1433"
    networks:
      - app-network
    volumes:
          - mssql_data:/var/opt/mssql #to persist data

  backend:
    build: .
    container_name: online-banking-backend
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=OnlineBanking;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=yourStrong(!)Password

  frontend:
    build:
      context: ../online-banking-frontend
      dockerfile: Dockerfile
    container_name: online-banking-frontend
    ports:
      - "3000:3000" # Maps React frontend to localhost:3000
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
          - ../online-banking-frontend:/app  # Mount frontend source code
          - /app/node_modules                 # Anonymous volume to avoid overwriting node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true npm start
    command: npm start -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data: